backend:
  name: github
  repo: officebuilding709/Alamgir.Malek # আপনার গিটহাব ইউজারনেম এবং রিপোর নাম
  branch: main # আপনার রিপোর মেইন ব্রাঞ্চ (main বা master)
  base_url: https://sveltia-cms-auth.officebuilding709.workers.dev # এখানে আপনার ক্লাউডফ্লেয়ারের লিংকটি বসান

media_folder: "images/uploads" # ছবি যেখানে আপলোড হবে
public_folder: "/images/uploads" # সাইটে ছবি যে পাথ থেকে লোড হবে

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
